version: '3.7'

services:
  nginx: 
    depends_on:
      - client
      - api
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 80:80
  client:
    stdin_open: true
    build:
      dockerfile: .docker/Dockerfile
      context: ./client/
    volumes:
      - /app/node_modules
      - ./client:/app
  db:
    image: postgres
    command: >
      -c max_wal_size=5GB
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: stocks
      POSTGRES_USER: stocks
      POSTGRES_PASSWORD: stocks
    restart: always
    volumes: 
      - ${PWD}/postgres:/var/lib/postgresql/data
  api:
    depends_on:
      - db
    build:
      dockerfile: .docker/Dockerfile
      context: ./server/
    volumes: 
      - ./server/:/var/www/html/
  fake:
    depends_on:
      - api
      - db
    build:
      dockerfile: .docker/Dockerfile
      context: ./fake/
    volumes:
      - ./fake/:/app
    env_file:
      - ./fake/.env
